services:
  backend:
    image: superchatbot_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env

  frontend:
    image: superchatbot_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
